Repository Solvro/backend-wakacyjne-wyzwanie-2025-zadania, pull requests merged in 2025-08, with the labels that each got.

#12 Rozwiązanie zadania 0
  intex.ts
Labels: size/S

#9 Rozwiązanie zadania 0
  index.ts
Labels: size/S

#36 feat: Task 0 solution
  index.ts
Labels: size/S

#58 feat: solution task 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  README.md
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#55 Task 1 solution
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#80 Mikolaj kaminski 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#39 Jakub Kobus - task 0
  .gitignore
  index.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: size/M

#41 Jakub kobus - task 1
  .commitlintrc.js
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  README.md
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/XL

#77 Dawid Błaszczyk - Zadanie 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/interfaces/json-request.interface.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#34 Zadanie 0
  .gitignore
  package-lock.json
  package.json
  src/intex.ts
  tsconfig.json
Labels: size/M

#47 Task 1 done
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#100 feat: database
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250816094116_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.spec.ts
  src/prisma/prisma.service.ts
Labels: size/L

#53 Radek rudzinski 1
  .commitlintrc.js
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  README.md
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#33 feat: add solution for task 0
  intex.ts
Labels: size/S

#74 Solution for task 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#70 Task 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#87 Amelia Sroczyńska Zadanie 1
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: size/L

#113 feat/ Dominik Kaczmarek lista 2
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250820160501_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.ts
Labels: size/L

#119 Bartosz krzysztoszek 2
  .gitignore
  diagram.png
  package-lock.json
  package.json
  prisma/migrations/20250818174818_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.ts
  test/app.e2e-spec.ts
Labels: size/L

#138 Wojciech Dominiak - task 2
  docker-compose.yml
  index.ts
  package-lock.json
  package.json
  prisma/migrations/20250823150609_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.ts
  test/app.e2e-spec.ts
Labels: size/L

#105 Task 2 solution
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250822153258_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.ts
Labels: size/L

#131 Jakub Ptak zadanie 2
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250825181928_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
  test/app.e2e-spec.ts
Labels: size/L

#124 Dawid Błaszczyk - Zadanie 2
  .env.example
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250819152005_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.ts
Labels: size/L

#146 feat: implemented crud for expenses and partcipant, created dto's, in…
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
Labels: size/XL

#99 Jan Juskowiak - zadanie 2
  .gitignore
  .husky/_/.gitignore
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  dbdiag.png
  package-lock.json
  package.json
  prisma/migrations/20250814151436_init/migration.sql
  prisma/migrations/20250814171525_add_email_to_participant/migration.sql
  prisma/migrations/20250815170120_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/database.service.ts
  test.py
  test/app.e2e-spec.ts
Labels: size/L

#136 Dominik dabrowski 2
  .gitignore
  intex.ts
  package-lock.json
  package.json
  prisma/migrations/20250827121218_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
Labels: size/L

#145 Jakub wieśniak - zadanie 2
  baza.png
  prisma/migrations/20250825180936_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
Labels: size/L

#155 Jakub kobus - task 3
  .env.example
  package-lock.json
  package.json
  prisma/migrations/20250826190902_1/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.controller.ts
  src/app.module.ts
  src/expenses/dto/create-expense.dto.ts
  src/expenses/dto/expense-response.dto.ts
  src/expenses/dto/update-expense.dto.ts
  src/expenses/expenses.controller.ts
  src/expenses/expenses.module.ts
  src/expenses/expenses.service.ts
  src/main.ts
  src/participants/dto/create-participant.dto.ts
  src/participants/dto/participant-response.dto.ts
  src/participants/dto/update-participant.dto.ts
  src/participants/participants.controller.ts
  src/participants/participants.module.ts
  src/participants/participants.service.ts
  src/persons/dto/create-person.dto.ts
  src/persons/dto/person-response.dto.ts
  src/persons/dto/update-person.dto.ts
  src/persons/persons.controller.ts
  src/persons/persons.module.ts
  src/persons/persons.service.ts
  src/prisma/ERD.png
  src/prisma/prisma.controller.ts
  src/trips/dto/create-trip.dto.ts
  src/trips/dto/trip-response.dto.ts
  src/trips/dto/update-trip.dto.ts
  src/trips/trips.controller.ts
  src/trips/trips.module.ts
  src/trips/trips.service.ts
Labels: size/XXL

#118 Solution Task 2 Patryk Mikołajewicz
  .github/workflows/ci.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  prisma/migrations/20250818162656_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/prisma/ERD.png
  src/prisma/Endpoint_get.png
  src/prisma/Endpoint_put.png
  src/prisma/prisma.controller.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.ts
  tsconfig.json
Labels: size/L

#134 Jan Druszcz - task 2
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250827212311_add_payer_to_expense/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: size/L

#157 feat/ Dominik kaczmarek lista 3
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.controller.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/expense-response.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/participant-response.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip-participants/dto/create-trip-participant.dto.ts
  src/trip-participants/dto/trip-participant-response.dto.ts
  src/trip-participants/trip-participants.controller.spec.ts
  src/trip-participants/trip-participants.controller.ts
  src/trip-participants/trip-participants.module.ts
  src/trip-participants/trip-participants.service.spec.ts
  src/trip-participants/trip-participants.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/trip-response.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
Labels: size/XXL
