Repository Solvro/backend-wakacyjne-wyzwanie-2025-zadania, pull requests merged in 2025-09, with the labels that each got.

#150 Task 3 solution
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.ts
Labels: size/L

#35 Zadanie 0
  index.ts
Labels: size/S

#162 Wojciech Dominiak - task 3
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/expense-response.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/entities/expense.entity.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/participant-response.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/entities/participant.entity.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  test/app.e2e-spec.ts
Labels: size/XL

#183 Jan Druszcz - task 3
  package-lock.json
  package.json
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/expense-response.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/entities/expense.entity.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/participant-response.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/entities/participant.entity.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip/dto/add-participant.dto.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/trip-response.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/entities/trip.entity.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
  test/jest-e2e.json
Labels: size/XL

#179 feat: task 2 solution Krystian Śliwiński
  package-lock.json
  package.json
  prisma/migrations/20250902181717_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
Labels: size/L

#69 Exercise 1 finished
  .commitlintrc.mjs
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  ProofOfWorking.PNG
  README.md
  ellipsis.yaml
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
Labels: size/L

#188 3. Amelia Sroczyńska
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/entities/expense.entity.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/entities/participant.entity.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip-participant/dto/create-trip-participant.dto.ts
  src/trip-participant/dto/update-trip-participant.dto.ts
  src/trip-participant/entities/trip-participant.entity.ts
  src/trip-participant/trip-participant.controller.spec.ts
  src/trip-participant/trip-participant.controller.ts
  src/trip-participant/trip-participant.module.ts
  src/trip-participant/trip-participant.service.spec.ts
  src/trip-participant/trip-participant.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/entities/trip.entity.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
  test/app.e2e-spec.ts
Labels: size/XXL

#199 Dominik dabrowski 4
  package-lock.json
  package.json
  prisma/migrations/20250908181431_/migration.sql
  prisma/migrations/20250908182204_init/migration.sql
  prisma/migrations/20250909144510_init/migration.sql
  prisma/migrations/20250910180836_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/login-response.dto.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/register.dto.ts
  src/auth/roles/role.decorator.ts
  src/auth/roles/trip-role.decorator.ts
  src/auth/roles/trip-role.guard.ts
  src/auth/roles/user-role.guard.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/participant.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/trip-private-response.dto.ts
  src/trip/dto/trip-response.dto.ts
  src/trip/trip.controller.ts
  src/trip/trip.service.ts
  src/user/dto/update-user.dto.ts
  src/user/dto/user-metadata.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/validators/email-parameter.dto.ts
  src/validators/future-date.validator.ts
  src/validators/id-parameter.dto.ts
Labels: size/XXL

#187 Jan Juskowiak - task 4
  package-lock.json
  package.json
  prisma/migrations/20250903200053_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/login-response.dto.ts
  src/auth/login.dto.ts
  src/auth/roles/roles.decorator.ts
  src/auth/roles/roles.guard.ts
  src/auth/user-request.dto.ts
  src/database/database.controller.ts
  src/database/database.service.ts
  src/expense/create-expense.dto.ts
  src/expense/expense.controller.ts
  src/expense/expense.service.ts
  src/participant/create-participant.dto.ts
  src/participant/participant.service.ts
  src/participant/patricipant.controller.ts
  src/participant/update-participant.dto.ts
  src/user/create-user.dto.ts
  src/user/metadata-user.ts
  src/user/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  test.py
  test/app.e2e-spec.ts
Labels: size/XL

#200 Maria peregudova 3
  .github/workflows/ci.yml
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/database/database.controller.ts
  src/database/database.module.ts
  src/database/database.service.spec.ts
  src/database/database.service.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/response-expense.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/main.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/response-participant.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/response-trip.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
Labels: size/XXL

#193 feat/ Dominik Kaczmarek 5
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/auth/auth.guard.spec.ts
  src/expense/dto/expense-response.dto.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/participant/dto/participant-response.dto.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.module.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip-participants/trip-participants.controller.ts
  src/trip-participants/trip-participants.module.ts
  src/trip-participants/trip-participants.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/trip-response-private.dto.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  src/validators/end-after-start.validator.spec.ts
  test/app.e2e-spec.ts
  test/clean-database.ts
  test/expense.e2e-spec.ts
  test/participant.e2e-spec.ts
  test/seed-database.ts
  test/trip.e2e-spec.ts
Labels: size/XXL

#220 Dominik dabrowski 5
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/auth/auth.controller.spec.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/roles/role.guard.spec.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.controller.ts
  src/expense/expense.service.spec.ts
  src/main.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.controller.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.service.spec.ts
  src/user/user.controller.spec.ts
  src/user/user.service.spec.ts
  src/validators/future-date.spec.ts
  test/app.e2e-spec.ts
  test/expense.e2e-spec.ts
  test/jest-e2e.json
  test/participant.e2e-spec.ts
  test/trips.e2e-spec.ts
  test/utils/clean-database.ts
  test/utils/seed-database.ts
Labels: size/XXL

#213 Kamil Sztabert - task 5
  .github/workflows/ci.yml
  package.json
  src/auth/auth.guard.spec.ts
  src/auth/roles/role.guard.spec.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.service.spec.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.service.spec.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.service.spec.ts
  src/user/user.controller.spec.ts
  src/user/user.service.spec.ts
  src/validators/date.validator.spec.ts
  src/validators/password.validator.spec.ts
  src/validators/text.validator.spec.ts
  test/clean-database.ts
  test/expense.e2e-spec.ts
  test/jest-e2e.json
  test/participant.e2e-spec.ts
  test/seed-database.ts
  test/test-setup.ts
  test/trip.e2e-spec.ts
  test/user.e2e-spec.ts
Labels: size/XXL

#203 Dawid Błaszczyk - Zadanie 5
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.service.spec.ts
  src/auth/guards/custom-token.guard.spec.ts
  src/auth/guards/roles.guard.spec.ts
  src/auth/guards/roles.guard.ts
  src/common/validators/past-date.validator.spec.ts
  src/enums/enums.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.service.spec.ts
  src/participant/participant.service.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/trip-response.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.controller.ts
  src/trip/trip.module.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
  src/user/user.module.ts
  test/app.e2e-spec.ts
  test/clean-database.ts
  test/expenses.e2e-spec.ts
  test/jest-e2e.json
  test/participants.e2e-spec.ts
  test/seed-database.ts
  test/trips.e2e-spec.ts
Labels: size/XXL

#239 Kamil Sztabert - task 6
  .github/workflows/ci.yml
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20250919185507_add_currency_exchange_rate_payment/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/activity/dto/activity-response.dto.ts
  src/activity/dto/create-activity.dto.ts
  src/activity/dto/update-activity.dto.ts
  src/app.module.ts
  src/currency/currency-expense.service.ts
  src/currency/currency-scheduler.service.ts
  src/currency/currency-scraper.controller.ts
  src/currency/currency-scraper.service.ts
  src/currency/currency.controller.spec.ts
  src/currency/currency.controller.ts
  src/currency/currency.module.ts
  src/currency/currency.service.spec.ts
  src/currency/currency.service.ts
  src/currency/dto/create-currency.dto.ts
  src/currency/dto/currency-metadata.dto.ts
  src/currency/dto/exchange-rate-history.dto.ts
  src/currency/dto/exchange-rate-metadata.dto.ts
  src/currency/dto/update-currency.dto.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/expense-metadata.dto.ts
  src/expense/dto/expense-response.dto.ts
  src/expense/expense.controller.spec.ts
  src/expense/expense.module.ts
  src/expense/expense.service.spec.ts
  src/expense/expense.service.ts
  src/participant/dto/participant-response.dto.ts
  src/participant/participant.controller.spec.ts
  src/participant/participant.service.spec.ts
  src/payment/dto/create-payment.dto.ts
  src/payment/dto/payment-response.dto.ts
  src/payment/dto/update-payment.dto.ts
  src/payment/payment.controller.spec.ts
  src/payment/payment.controller.ts
  src/payment/payment.module.ts
  src/payment/payment.service.spec.ts
  src/payment/payment.service.ts
  src/trip/dto/trip-response.dto.ts
  src/trip/trip.controller.spec.ts
  src/trip/trip.service.spec.ts
  src/trip/trip.service.ts
  test/jest-e2e.json
  test/seed-database.ts
  test/trip.e2e-spec.ts
  test/user.e2e-spec.ts
Labels: size/XXL

#240 Jan druszcz 6
  package-lock.json
  package.json
  prisma/migrations/20250921181930_add_currency_rate/migration.sql
  prisma/migrations/20250921182841_add_unique_code_to_currency_rate/migration.sql
  prisma/migrations/20250922104512_update_payment_currency_enum/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/currency/currency.controller.spec.ts
  src/currency/currency.controller.ts
  src/currency/currency.enum.ts
  src/currency/currency.module.ts
  src/currency/currency.scraper.ts
  src/currency/currency.service.spec.ts
  src/currency/currency.service.ts
  src/currency/dto/create-currency.dto.ts
  src/currency/dto/currency-response.dto.ts
  src/currency/dto/update-currency.dto.ts
  src/database/database.service.ts
  src/participant/participant.service.ts
  src/payment/dto/create-payment.dto.ts
  src/payment/dto/update-payment.dto.ts
  src/payment/payment.controller.spec.ts
  src/payment/payment.controller.ts
  src/payment/payment.module.ts
  src/payment/payment.service.spec.ts
  src/payment/payment.service.ts
Labels: size/L

#214 feat/ Dominik Kaczmarek 6
  package-lock.json
  package.json
  prisma/migrations/20250901113610_add_user_table/migration.sql
  prisma/migrations/20250915093619_add_user_and_currency_tables/migration.sql
  prisma/migrations/20250915164403_add_payment_table/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/currencies/currencies.controller.ts
  src/currencies/currencies.module.ts
  src/currencies/currencies.service.ts
  src/currencies/currency-scraper.service.ts
  src/currencies/dto/create-or-update-currency.dto.ts
  src/currencies/dto/currency-response.dto.ts
  src/payments/dto/create-payment.dto.ts
  src/payments/dto/payment-response.dto.ts
  src/payments/payments.controller.ts
  src/payments/payments.module.ts
  src/payments/payments.service.ts
  src/validators/is-valid-currency-code.validator.ts
Labels: size/XL

#224 Jakub ptak 4
  .github/workflows/ci.yml
  package-lock.json
  package.json
  prisma/migrations/20250916223405_/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/request-with-user.dto.ts
  src/auth/dto/response-login.dto.ts
  src/auth/roles/role.decorator.ts
  src/auth/roles/role.guard.ts
  src/expense/dto/create-expense.dto.ts
  src/expense/dto/response-expense.dto.ts
  src/expense/dto/update-expense.dto.ts
  src/participant/dto/create-participant.dto.ts
  src/participant/dto/response-participant.dto.ts
  src/participant/dto/update-participant.dto.ts
  src/trip/dto/create-trip.dto.ts
  src/trip/dto/response-trip.dto.ts
  src/trip/dto/update-trip.dto.ts
  src/user/dto/register-user.dto.ts
  src/user/dto/update-response-user.ts
  src/user/dto/update-user.dto.ts
  src/user/dto/user-metadata.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/validators/nice-age.ts
  src/validators/nice-date.ts
Labels: size/XL
